//#line 2 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the aquajoy package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __aquajoy__AQUATELEOPJOYCONFIG_H__
#define __aquajoy__AQUATELEOPJOYCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace aquajoy
{
  class AquaTeleopJoyConfigStatics;
  
  class AquaTeleopJoyConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(AquaTeleopJoyConfig &config, const AquaTeleopJoyConfig &max, const AquaTeleopJoyConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const AquaTeleopJoyConfig &config1, const AquaTeleopJoyConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, AquaTeleopJoyConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const AquaTeleopJoyConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, AquaTeleopJoyConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const AquaTeleopJoyConfig &config) const = 0;
      virtual void getValue(const AquaTeleopJoyConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T AquaTeleopJoyConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (AquaTeleopJoyConfig::* field);

      virtual void clamp(AquaTeleopJoyConfig &config, const AquaTeleopJoyConfig &max, const AquaTeleopJoyConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const AquaTeleopJoyConfig &config1, const AquaTeleopJoyConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, AquaTeleopJoyConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const AquaTeleopJoyConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, AquaTeleopJoyConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const AquaTeleopJoyConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const AquaTeleopJoyConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, AquaTeleopJoyConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, AquaTeleopJoyConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<AquaTeleopJoyConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(AquaTeleopJoyConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("joy_axis_deadzone"==(*_i)->name){joy_axis_deadzone = boost::any_cast<double>(val);}
        if("max_speed_cmd"==(*_i)->name){max_speed_cmd = boost::any_cast<double>(val);}
        if("max_heave_cmd"==(*_i)->name){max_heave_cmd = boost::any_cast<double>(val);}
        if("max_roll_cmd"==(*_i)->name){max_roll_cmd = boost::any_cast<double>(val);}
        if("max_pitch_cmd"==(*_i)->name){max_pitch_cmd = boost::any_cast<double>(val);}
        if("max_yaw_cmd"==(*_i)->name){max_yaw_cmd = boost::any_cast<double>(val);}
        if("max_roll_pos"==(*_i)->name){max_roll_pos = boost::any_cast<double>(val);}
        if("max_pitch_pos"==(*_i)->name){max_pitch_pos = boost::any_cast<double>(val);}
        if("max_yaw_pos"==(*_i)->name){max_yaw_pos = boost::any_cast<double>(val);}
        if("min_depth"==(*_i)->name){min_depth = boost::any_cast<double>(val);}
        if("max_depth"==(*_i)->name){max_depth = boost::any_cast<double>(val);}
        if("default_fixed_depth"==(*_i)->name){default_fixed_depth = boost::any_cast<double>(val);}
        if("max_roll_vel"==(*_i)->name){max_roll_vel = boost::any_cast<double>(val);}
        if("max_pitch_vel"==(*_i)->name){max_pitch_vel = boost::any_cast<double>(val);}
        if("max_yaw_vel"==(*_i)->name){max_yaw_vel = boost::any_cast<double>(val);}
        if("max_depth_vel"==(*_i)->name){max_depth_vel = boost::any_cast<double>(val);}
      }
    }

    double joy_axis_deadzone;
double max_speed_cmd;
double max_heave_cmd;
double max_roll_cmd;
double max_pitch_cmd;
double max_yaw_cmd;
double max_roll_pos;
double max_pitch_pos;
double max_yaw_pos;
double min_depth;
double max_depth;
double default_fixed_depth;
double max_roll_vel;
double max_pitch_vel;
double max_yaw_vel;
double max_depth_vel;

    bool state;
    std::string name;

    
}groups;



//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double joy_axis_deadzone;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double max_speed_cmd;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double max_heave_cmd;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double max_roll_cmd;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double max_pitch_cmd;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double max_yaw_cmd;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double max_roll_pos;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double max_pitch_pos;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double max_yaw_pos;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double min_depth;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double max_depth;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double default_fixed_depth;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double max_roll_vel;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double max_pitch_vel;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double max_yaw_vel;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double max_depth_vel;
//#line 218 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("AquaTeleopJoyConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const AquaTeleopJoyConfig &__max__ = __getMax__();
      const AquaTeleopJoyConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const AquaTeleopJoyConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const AquaTeleopJoyConfig &__getDefault__();
    static const AquaTeleopJoyConfig &__getMax__();
    static const AquaTeleopJoyConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const AquaTeleopJoyConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void AquaTeleopJoyConfig::ParamDescription<std::string>::clamp(AquaTeleopJoyConfig &config, const AquaTeleopJoyConfig &max, const AquaTeleopJoyConfig &min) const
  {
    return;
  }

  class AquaTeleopJoyConfigStatics
  {
    friend class AquaTeleopJoyConfig;
    
    AquaTeleopJoyConfigStatics()
    {
AquaTeleopJoyConfig::GroupDescription<AquaTeleopJoyConfig::DEFAULT, AquaTeleopJoyConfig> Default("Default", "", 0, 0, true, &AquaTeleopJoyConfig::groups);
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.joy_axis_deadzone = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.joy_axis_deadzone = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.joy_axis_deadzone = 0.15;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("joy_axis_deadzone", "double", 0, "Deadzone range on individual joypad analog axes", "", &AquaTeleopJoyConfig::joy_axis_deadzone)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("joy_axis_deadzone", "double", 0, "Deadzone range on individual joypad analog axes", "", &AquaTeleopJoyConfig::joy_axis_deadzone)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.max_speed_cmd = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.max_speed_cmd = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.max_speed_cmd = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_speed_cmd", "double", 0, "Maximum speed command magnitude [for all modes]", "", &AquaTeleopJoyConfig::max_speed_cmd)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_speed_cmd", "double", 0, "Maximum speed command magnitude [for all modes]", "", &AquaTeleopJoyConfig::max_speed_cmd)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.max_heave_cmd = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.max_heave_cmd = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.max_heave_cmd = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_heave_cmd", "double", 0, "Maximum heave command magnitude [for non-depth-reg. modes]", "", &AquaTeleopJoyConfig::max_heave_cmd)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_heave_cmd", "double", 0, "Maximum heave command magnitude [for non-depth-reg. modes]", "", &AquaTeleopJoyConfig::max_heave_cmd)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.max_roll_cmd = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.max_roll_cmd = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.max_roll_cmd = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_roll_cmd", "double", 0, "Maximum roll command magnitude [for non-AP mode]", "", &AquaTeleopJoyConfig::max_roll_cmd)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_roll_cmd", "double", 0, "Maximum roll command magnitude [for non-AP mode]", "", &AquaTeleopJoyConfig::max_roll_cmd)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.max_pitch_cmd = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.max_pitch_cmd = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.max_pitch_cmd = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_pitch_cmd", "double", 0, "Maximum pitch command magnitude [for non-AP mode]", "", &AquaTeleopJoyConfig::max_pitch_cmd)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_pitch_cmd", "double", 0, "Maximum pitch command magnitude [for non-AP mode]", "", &AquaTeleopJoyConfig::max_pitch_cmd)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.max_yaw_cmd = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.max_yaw_cmd = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.max_yaw_cmd = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_yaw_cmd", "double", 0, "Maximum yaw command magnitude [for non-AP mode]", "", &AquaTeleopJoyConfig::max_yaw_cmd)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_yaw_cmd", "double", 0, "Maximum yaw command magnitude [for non-AP mode]", "", &AquaTeleopJoyConfig::max_yaw_cmd)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.max_roll_pos = -180.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.max_roll_pos = 180.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.max_roll_pos = 90.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_roll_pos", "double", 0, "Analog stick to roll position ratio (deg) [for AP-pos. modes]", "", &AquaTeleopJoyConfig::max_roll_pos)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_roll_pos", "double", 0, "Analog stick to roll position ratio (deg) [for AP-pos. modes]", "", &AquaTeleopJoyConfig::max_roll_pos)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.max_pitch_pos = -180.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.max_pitch_pos = 180.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.max_pitch_pos = 90.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_pitch_pos", "double", 0, "Analog stick to pitch position ratio (deg) [for AP-pos. modes]", "", &AquaTeleopJoyConfig::max_pitch_pos)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_pitch_pos", "double", 0, "Analog stick to pitch position ratio (deg) [for AP-pos. modes]", "", &AquaTeleopJoyConfig::max_pitch_pos)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.max_yaw_pos = -180.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.max_yaw_pos = 180.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.max_yaw_pos = 180.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_yaw_pos", "double", 0, "Analog stick to yaw position ratio (deg) [UNUSED]", "", &AquaTeleopJoyConfig::max_yaw_pos)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_yaw_pos", "double", 0, "Analog stick to yaw position ratio (deg) [UNUSED]", "", &AquaTeleopJoyConfig::max_yaw_pos)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.min_depth = -2.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.min_depth = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.min_depth = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("min_depth", "double", 0, "Minimum depth (m) [for AP-depth-reg. modes]", "", &AquaTeleopJoyConfig::min_depth)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("min_depth", "double", 0, "Minimum depth (m) [for AP-depth-reg. modes]", "", &AquaTeleopJoyConfig::min_depth)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.max_depth = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.max_depth = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.max_depth = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_depth", "double", 0, "Maximum depth (m) [for AP-depth-reg. modes]", "", &AquaTeleopJoyConfig::max_depth)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_depth", "double", 0, "Maximum depth (m) [for AP-depth-reg. modes]", "", &AquaTeleopJoyConfig::max_depth)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.default_fixed_depth = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.default_fixed_depth = 10.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.default_fixed_depth = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("default_fixed_depth", "double", 0, "Use fixed initial depth upon entering depth-related modes [if < 0, then initial depth is current robot depth]", "", &AquaTeleopJoyConfig::default_fixed_depth)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("default_fixed_depth", "double", 0, "Use fixed initial depth upon entering depth-related modes [if < 0, then initial depth is current robot depth]", "", &AquaTeleopJoyConfig::default_fixed_depth)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.max_roll_vel = -1800.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.max_roll_vel = 1800.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.max_roll_vel = 450.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_roll_vel", "double", 0, "Analog stick to roll velocity ratio (deg/s) [for AP-pos. modes]", "", &AquaTeleopJoyConfig::max_roll_vel)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_roll_vel", "double", 0, "Analog stick to roll velocity ratio (deg/s) [for AP-pos. modes]", "", &AquaTeleopJoyConfig::max_roll_vel)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.max_pitch_vel = -1800.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.max_pitch_vel = 1800.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.max_pitch_vel = 450.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_pitch_vel", "double", 0, "Analog stick to pitch velocity ratio (deg/s) [for AP-pos. modes]", "", &AquaTeleopJoyConfig::max_pitch_vel)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_pitch_vel", "double", 0, "Analog stick to pitch velocity ratio (deg/s) [for AP-pos. modes]", "", &AquaTeleopJoyConfig::max_pitch_vel)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.max_yaw_vel = -1800.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.max_yaw_vel = 1800.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.max_yaw_vel = 900.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_yaw_vel", "double", 0, "Analog stick to yaw velocity ratio (deg/s) [for AP-pos. modes]", "", &AquaTeleopJoyConfig::max_yaw_vel)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_yaw_vel", "double", 0, "Analog stick to yaw velocity ratio (deg/s) [for AP-pos. modes]", "", &AquaTeleopJoyConfig::max_yaw_vel)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.max_depth_vel = -10.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.max_depth_vel = 10.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.max_depth_vel = 3.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_depth_vel", "double", 0, "Analog stick to depth velocity ratio (m/s) [for AP-pos. modes]", "", &AquaTeleopJoyConfig::max_depth_vel)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr(new AquaTeleopJoyConfig::ParamDescription<double>("max_depth_vel", "double", 0, "Analog stick to depth velocity ratio (m/s) [for AP-pos. modes]", "", &AquaTeleopJoyConfig::max_depth_vel)));
//#line 233 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 233 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(AquaTeleopJoyConfig::AbstractGroupDescriptionConstPtr(new AquaTeleopJoyConfig::GroupDescription<AquaTeleopJoyConfig::DEFAULT, AquaTeleopJoyConfig>(Default)));
//#line 353 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"

      for (std::vector<AquaTeleopJoyConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<AquaTeleopJoyConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    AquaTeleopJoyConfig __max__;
    AquaTeleopJoyConfig __min__;
    AquaTeleopJoyConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const AquaTeleopJoyConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static AquaTeleopJoyConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &AquaTeleopJoyConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const AquaTeleopJoyConfig &AquaTeleopJoyConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const AquaTeleopJoyConfig &AquaTeleopJoyConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const AquaTeleopJoyConfig &AquaTeleopJoyConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<AquaTeleopJoyConfig::AbstractParamDescriptionConstPtr> &AquaTeleopJoyConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<AquaTeleopJoyConfig::AbstractGroupDescriptionConstPtr> &AquaTeleopJoyConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const AquaTeleopJoyConfigStatics *AquaTeleopJoyConfig::__get_statics__()
  {
    const static AquaTeleopJoyConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = AquaTeleopJoyConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __AQUATELEOPJOYRECONFIGURATOR_H__
