<?xml version="1.0"?>

<!-- The Aqua URDF specifies the positions of the robot's sensors and actuators.
     It can be parsed by the xacro package to be translated into tf frames and 
     a robot model compatible with rviz for vizualization.

     Author: Dave Meger, Anqi Xu, Bikram Dey
     Date:   Nov 21, 2012

     Revision history:

     Rev1:  Basic box shaped model and legs that can be actuated as revolute joints.
         Rev2:  Added 3D mesh of aqua with help from Anqi and Bikram.
         Rev3:  Added frames for cameras.
         Rev4:  Updated to Hydro/Indigo xacro compatibility
 -->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="aqua">
    <xacro:include filename="$(find aqua_description)/urdf/materials.urdf.xacro" />

    <!-- ========= BEGIN CONSTANT DEFINITIONS =========== -->

    <xacro:property name="M_PI" value="3.1415926535897931" />

    <xacro:property name="shell_size_x" value="0.64" />
    <xacro:property name="shell_size_y" value="0.21" />
    <xacro:property name="shell_size_z" value="0.12" />

    <xacro:property name="leg_size_x" value="0.16" />
    <xacro:property name="leg_size_y" value="0.05" />
    <xacro:property name="leg_size_z" value="0.003" />

    <xacro:property name="hip_radius" value="0.029" />
    <xacro:property name="hip_length" value="0.032" />
    <xacro:property name="mid_hip_length" value="0.082"/>

    <xacro:property name="shoulder_size_x" value="0.06" />
    <xacro:property name="shoulder_size_y" value="0.035" />
    <xacro:property name="shoulder_size_z" value="0.02" />

    <xacro:property name="hip_mass" value="0.25"/>
    <xacro:property name="mid_hip_mass" value="0.5"/>
    <xacro:property name="shell_mass" value="14.4"/> <!-- total is 16.4 -->
    <xacro:property name="leg_mass" value="0.065"/>
    <xacro:property name="shoulder_mass" value="0.025"/>
    <xacro:property name="front_ballast_density" value="7140.0"/>
    <xacro:property name="ballast_plate_density" value="8050.0"/>

    <!-- ========= BEGIN MACRO DEFINITIONS =========== -->
    <!-- LEGS -->
    <xacro:macro name="leg" params="name">
        <link name="${name}_leg">
            <visual name="leg_visual">
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry name="leg_visual_geom">  
                    <box size="${leg_size_x} ${leg_size_y} ${leg_size_z}" />
                </geometry>
                <material name="White" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="${leg_size_x} ${leg_size_y} ${leg_size_z}" />
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <mass value="${leg_mass}"/>
                <inertia ixx="${leg_mass*(leg_size_y*leg_size_y + leg_size_z*leg_size_z)/12}" ixy="0.00" ixz="0.00" iyy="${leg_mass*(leg_size_x*leg_size_x + leg_size_z*leg_size_z)/12}" iyz="0.00" izz="${leg_mass*(leg_size_x*leg_size_x + leg_size_y*leg_size_y)/12}"/>
            </inertial>
        </link>
    </xacro:macro>

    <xacro:macro name="shoulder" params="name">
        <link name="${name}_shoulder">
            <visual name="shoulder_visual">
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry name="leg_joint_visual_geom">
                    <mesh filename="package://aqua_description/meshes/leg_joint.STL" scale="1.0 1.0 1.0" />
                </geometry>
                <material name="Black" />
            </visual>
            <collision>
                <origin xyz="-0.007 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="${shoulder_size_x} ${shoulder_size_y} ${shoulder_size_z}" />
                </geometry>
            </collision>
            <inertial>
                <origin xyz="-0.007 0 0" rpy="0 0 0" />
                <mass value="${shoulder_mass}"/>
                <inertia ixx="${shoulder_mass*(shoulder_size_y*shoulder_size_y + shoulder_size_z*shoulder_size_z)/12}" ixy="0.00" ixz="0.00" iyy="${shoulder_mass*(shoulder_size_x*shoulder_size_x + shoulder_size_z*shoulder_size_z)/12}" iyz="0.00" izz="${shoulder_mass*(shoulder_size_x*shoulder_size_x + leg_size_y*leg_size_y)/12}"/>
            </inertial>
        </link>
    </xacro:macro>

    <!-- HIPS -->
    <xacro:macro name="hip" params="name xyz rpy">
        <link name ="${name}_hip">
            <collision>
                <origin xyz="${xyz}" rpy="${rpy}" />
                <geometry>
                    <cylinder length="${hip_length}" radius="${hip_radius}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="${xyz}" rpy="${rpy}" />
                <mass value="${hip_mass}"/>
                <inertia ixx="${hip_mass*(3*hip_radius*hip_radius+hip_length*hip_length)/12}" ixy="0.00" ixz="0.00" iyy="${hip_mass*(3*hip_radius*hip_radius+hip_length*hip_length)/12}" iyz="0.00" izz="${hip_mass*(hip_radius*hip_radius)/2}"/>
            </inertial>
        </link>
    </xacro:macro>

    <xacro:macro name="mid_hip" params="name xyz rpy">
        <link name ="${name}_hip">
            <collision>
                <origin xyz="${xyz}" rpy="${rpy}" />
                <geometry>
                    <cylinder length="${mid_hip_length}" radius="${hip_radius}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="${xyz}" rpy="${rpy}" />
                <mass value="${mid_hip_mass}"/>
                <inertia ixx="${mid_hip_mass*(3*hip_radius*hip_radius+mid_hip_length*mid_hip_length)/12}" ixy="0.00" ixz="0.00" iyy="${mid_hip_mass*(3*hip_radius*hip_radius+mid_hip_length*mid_hip_length)/12}" iyz="0.00" izz="${mid_hip_mass*(hip_radius*hip_radius)/2}"/>
            </inertial>
        </link>
    </xacro:macro>

    <!-- ballasting -->
    <xacro:macro name="rectangular_ballast_weight" params="name xyz rpy density length width height">
        <link name="${name}_ballast">
            <visual name="ballast_visual">
                <origin xyz="${xyz}" rpy="${rpy}" />
                <geometry name="left_front_leg_visual_geom">  
                    <box size="${length} ${width} ${height}" />
                </geometry>
                <material name="Gray" />
            </visual>
            <inertial>
                <origin xyz="${xyz}" rpy="${rpy}" />
                <mass value="${density*length*width*height}"/>
                <inertia ixx="${(density*length*width*height)*(width*width + height*height)/12}" ixy="0.00" ixz="0.00" iyy="${(density*length*width*height)*(length*length + height*height)/12}" iyz="0.00" izz="${(density*length*width*height)*(length*length + width*width)/12}"/>
            </inertial>
        </link>
        <joint name="base_joint_${name}" type="revolute">
            <limit upper="0.0" lower="0.0" effort="0.0" velocity="0.0"/>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <axis xyz="0 1 0" />
            <parent link="aqua_base"/>
            <child link="${name}_ballast"/>
        </joint>
    </xacro:macro>

    <!-- LEG JOINTS -->
    <xacro:macro name="hip_joint" params="name xyz rpy axis">
        <joint name="${name}_hip_joint" type="fixed">
            <!--joint name="${name}_hip_joint" type="revolute">
      <limit upper="0.0" lower="0.0" effort="0.0" velocity="0.0"/-->
      <origin xyz="${xyz}" rpy="${rpy}" />
      <axis xyz="${axis}" />
      <parent link="aqua_side_plates"/>
      <child link="${name}_hip"/>
  </joint>
  </xacro:macro>

  <xacro:macro name="leg_joint" params="name xyz rpy axis">
      <joint name="${name}_leg_joint" type="continuous">
          <origin xyz="${xyz}" rpy="${rpy}" />
          <dynamics damping="0.1"/>
          <axis xyz="${axis}" />
          <parent link="${name}_hip"/>
          <child link="${name}_shoulder"/>
      </joint>
  </xacro:macro>

  <xacro:macro name="shoulder_joint" params="name">
      <joint name="${name}_shoulder_joint" type="revolute">
          <limit upper="0.0" lower="0.0" effort="0.0" velocity="0.0"/>
          <dynamics damping="1000.0"/>
          <origin xyz="-${0.008 + leg_size_x/2} 0 -${leg_size_z/2}" rpy="0 0 0" />
          <axis xyz="0 1 0" />
          <parent link="${name}_shoulder"/>
          <child link="${name}_leg"/>
      </joint>
  </xacro:macro>

  <!-- GAZEBO MACROS -->
  <xacro:macro name="leg_gazebo" params="name">
      <gazebo reference="${name}_leg">
          <material>Gazebo/Red</material>
          <selfCollide>false</selfCollide>
          <dampingFactor>0.0001</dampingFactor>
      </gazebo>
      <gazebo reference="${name}_leg_joint">
          <implicitSpringDamper>true</implicitSpringDamper>
      </gazebo>
  </xacro:macro>

  <xacro:macro name="shoulder_gazebo" params="name">
      <gazebo reference="${name}_shoulder">
          <material>Gazebo/Black</material>
          <selfCollide>false</selfCollide>
          <dampingFactor>0.0001</dampingFactor>
      </gazebo>
      <gazebo reference="${name}_shoulder_joint">
          <implicitSpringDamper>true</implicitSpringDamper>
      </gazebo>
  </xacro:macro>

  <!-- ========= BEGIN LINK DEFINITIONS =========== -->

  <link name="aqua_base">
  </link>

  <!-- The parent link is the robots shell, silver and red in the same position -->
  <link name="aqua_side_plates">
      <visual name="side_plates_visual">
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry name="side_plates_geom">
              <mesh filename="package://aqua_description/meshes/aqua_red_m_low_res.STL" scale="1.0 1.0 1.0" />
          </geometry>
          <material name="Red"/>
      </visual>
  </link>

  <link name="aqua_shell">
      <visual name="shell_visual">
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry name="shell_visual_geom">
              <mesh filename="package://aqua_description/meshes/aqua_silver_m_low_res.STL" scale="1.0 1.0 1.0" />
          </geometry>
          <material name="Grey" />
      </visual>
      <collision>
          <geometry>
              <box size="${shell_size_x} ${shell_size_y} ${shell_size_z}"/>
          </geometry>
      </collision>
      <inertial>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <!-- the mass value came from the adept mobile robots datasheet -->
          <mass value="${shell_mass}"/>
          <!--inertia ixx="${shell_mass*(shell_size_y*shell_size_y + shell_size_z*shell_size_z)/12}" ixy="0.00" ixz="0.00" iyy="${shell_mass*(shell_size_x*shell_size_x + shell_size_z*shell_size_z)/12}" iyz="0.00" izz="${shell_mass*(shell_size_x*shell_size_x + shell_size_y*shell_size_y)/12}"/-->
          <!-- computed with meshlab -->
          <inertia ixx="${shell_mass*0.000014}" ixy="${shell_mass*0.000002}" ixz="0.00" iyy="${shell_mass*0.000073}" iyz="0.00" izz="${shell_mass*0.000080}"/>
      </inertial>
  </link>


  <!-- CAMERA LINKS -->

  <link name="camera_front_left">
      <visual name="camera_front_left_visual">
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry name="camera_front_left_visual_geom">  
              <box size="0 0 0" />
          </geometry>
          <material name="White" />
      </visual>
  </link>

  <link name="camera_front_right">
      <visual name="camera_front_right_visual">
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry name="camera_front_right_visual_geom">  
              <box size="0 0 0" />
          </geometry>
          <material name="White" />
      </visual>
  </link>

  <link name="camera_back_down">
      <visual name="camera_back_down_visual">
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry name="camera_back_down_visual_geom">  
              <box size="0 0 0" />
          </geometry>
          <material name="White" />
      </visual>
  </link>
  <!-- BALLASTING LINKS -->
  <xacro:rectangular_ballast_weight name="front_ballast_weight" 
                                    density="${front_ballast_density}" 
                                    xyz="${shell_size_x*0.375} ${0} ${-shell_size_z/2.0}" 
                                    rpy="0 0 ${M_PI/2}"
                                    length="0.10"
                                    width="0.025"
                                    height="0.0057"/>

  <!-- DEPTH SENSOR LINK -->
  <!--link name="depth_sensor">
    <visual name="depth_sensor_visual">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry name="depth_sensor_visual_geom">  
    <box size="0 0 0" />
      </geometry>
      <material name="White" />
    </visual>
    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" /-->
        <!-- these are dummy values, otherwise gazebo will ignore this link -->
        <!--mass value="${eps1}"/>
        <inertia ixx="${eps2}" ixy="0.00" ixz="0.00" iyy="${eps2}" iyz="0.00" izz="${eps2}"/>
    </inertial>
  </link-->

  <!-- FRONT LEFT LINKS -->

  <xacro:leg name="left_front"/>

  <xacro:shoulder name="left_front"/>

  <xacro:hip name="left_front" xyz="0 ${hip_length/2} 0" rpy="${M_PI/2} 0 0" />


  <!-- MID LEFT LINKS -->

  <xacro:leg name="left_mid"/>

  <xacro:shoulder name="left_mid"/>

  <xacro:mid_hip name="left_mid" xyz="0 ${mid_hip_length/2} 0" rpy="${M_PI/2} 0 0" />

  <!-- REAR LEFT LINKS -->

  <xacro:leg name="left_rear"/>

  <xacro:shoulder name="left_rear"/>

  <xacro:hip name ="left_rear" xyz="0 ${hip_length/2} 0" rpy="${M_PI/2} 0 0" />

  <!-- FRONT RIGHT LINKS -->

  <xacro:leg name="right_front"/>

  <xacro:shoulder name="right_front"/>

  <xacro:hip name ="right_front" xyz="0 -${hip_length/2} 0" rpy="${M_PI/2} 0 0" />

  <!-- MID RIGHT LINKS -->

  <xacro:leg name="right_mid"/>

  <xacro:shoulder name="right_mid"/>

  <xacro:mid_hip name="right_mid" xyz="0 -${mid_hip_length/2} 0" rpy="${M_PI/2} 0 0" />

  <!-- REAR RIGHT LINKS -->

  <xacro:leg name="right_rear"/>

  <xacro:shoulder name="right_rear"/>

  <xacro:hip name ="right_rear" xyz="0 -${hip_length/2} 0" rpy="${M_PI/2} 0 0" />

  <!-- ========= BEGIN JOINT DEFINITIONS =========== -->

  <!-- BASE JOINT -->

  <joint name="base_joint_sides" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <parent link="aqua_base"/>
      <child link="aqua_side_plates"/>
  </joint>

  <joint name="base_joint_shell" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <parent link="aqua_side_plates"/>
      <child link="aqua_shell"/>
  </joint>

  <!-- CAMERA JOINTS -->

  <joint name="front_left_camera_joint" type="fixed">
      <origin xyz="${shell_size_x/2} ${shell_size_y/3} 0" rpy="${M_PI/2} ${M_PI} ${M_PI/2}" />
      <axis xyz="0 1 0" />
      <parent link="aqua_shell"/>
      <child link="camera_front_left"/>
  </joint>

  <joint name="front_right_camera_joint" type="fixed">
      <origin xyz="${shell_size_x/2} -${shell_size_y/3} 0" rpy="${M_PI/2} ${M_PI} ${M_PI/2}" />
      <axis xyz="0 1 0" />
      <parent link="aqua_shell"/>
      <child link="camera_front_right"/>
  </joint>

  <joint name="back_down_camera_joint" type="fixed">
      <origin xyz="-${shell_size_x/2} 0 -${shell_size_z/2}" rpy="-${M_PI/2} ${M_PI/2} -${M_PI/2}" />
      <axis xyz="0 1 0" />
      <parent link="aqua_shell"/>
      <child link="camera_back_down"/>
  </joint>

  <!-- DEPTH SENSOR JOINT -->

  <!-- making this joint revolute instead of fixed is a hack, so that is appears in the gazebo simulation -->
  <!--joint name="depth_sensor_joint" type="revolute">
    <limit upper="0.0" lower="0.0" effort="0" velocity="0"/>
    <origin xyz="-${shell_size_x/2} 0 0" rpy="0 0 ${M_PI}" />
    <axis xyz="0 1 0" />
    <parent link="aqua_shell"/>
    <child link="depth_sensor"/>
  </joint -->

  <!-- FRONT LEFT JOINTS -->
  <xacro:hip_joint name="left_front" xyz="${shell_size_x/2 - 0.1027*shell_size_x} ${shell_size_y/2} 0" rpy="0 0 0" axis="0 1 0"/>

  <xacro:leg_joint name="left_front" xyz="0 ${leg_size_y/2 + hip_length} 0" rpy="0 0 0" axis="0 -1 0" />  

  <xacro:shoulder_joint name="left_front" />  

  <!-- MID LEFT JOINTS -->
  <xacro:hip_joint name="left_mid" xyz="0 ${shell_size_y/2} 0" rpy="0 0 0" axis="0 1 0" />  

  <xacro:leg_joint name="left_mid" xyz="0 ${leg_size_y/2 + mid_hip_length} 0" rpy="0 0 0" axis="0 -1 0"/>

  <xacro:shoulder_joint name="left_mid" />  

  <!-- REAR LEFT JOINTS -->
  <xacro:hip_joint name="left_rear" xyz="-${shell_size_x/2 - 0.1027*shell_size_x} ${shell_size_y/2} 0" rpy="0 0 0" axis="0 1 0" />  

  <xacro:leg_joint name="left_rear" xyz="0 ${leg_size_y/2 + hip_length} 0" rpy="0 0 0" axis="0 -1 0"/>

  <xacro:shoulder_joint name="left_rear" />  

  <!-- FRONT RIGHT JOINTS -->
  <xacro:hip_joint name="right_front" xyz="${shell_size_x/2 - 0.1026*shell_size_x} -${shell_size_y/2} 0" rpy="0 0 0" axis="0 1 0"/>

  <xacro:leg_joint name="right_front" xyz="0 -${leg_size_y/2 + hip_length} 0" rpy="0 0 0" axis="0 -1 0" />  

  <xacro:shoulder_joint name="right_front" />  

  <!-- MID RIGHT JOINTS -->
  <xacro:hip_joint name="right_mid" xyz="0 -${shell_size_y/2} 0" rpy="0 0 0" axis="0 1 0" />  

  <xacro:leg_joint name="right_mid" xyz="0 -${leg_size_y/2 + mid_hip_length} 0" rpy="0 0 0" axis="0 -1 0"/>

  <xacro:shoulder_joint name="right_mid" />  

  <!-- REAR RIGHT JOINTS -->
  <xacro:hip_joint name="right_rear" xyz="-${shell_size_x/2 - 0.1027*shell_size_x} -${shell_size_y/2} 0" rpy="0 0 0" axis="0 1 0" />  

  <xacro:leg_joint name="right_rear" xyz="0 -${leg_size_y/2 + hip_length} 0" rpy="0 0 0" axis="0 -1 0"/>

  <xacro:shoulder_joint name="right_rear" />  

  <!-- GAZEBO SPECIFIC SETTINGS -->
  <!-- gazebo materials -->
  <gazebo reference="aqua_side_plates">
      <material>Gazebo/Red</material>
      <selfCollide>false</selfCollide>
  </gazebo>
  <gazebo reference="aqua_shell">
      <material>Gazebo/Grey</material>
      <selfCollide>false</selfCollide>
  </gazebo>
  <gazebo reference="aqua_base">
      <selfCollide>false</selfCollide>
      <dampingFactor>0.000001</dampingFactor>
  </gazebo>
  <xacro:leg_gazebo name="left_front" />  
  <xacro:shoulder_gazebo name="left_front" />  
  <xacro:leg_gazebo name="left_mid" />  
  <xacro:shoulder_gazebo name="left_mid" />  
  <xacro:leg_gazebo name="left_rear" />  
  <xacro:shoulder_gazebo name="left_rear" />  
  <xacro:leg_gazebo name="right_front" />  
  <xacro:shoulder_gazebo name="right_front" />  
  <xacro:leg_gazebo name="right_mid" />  
  <xacro:shoulder_gazebo name="right_mid" />  
  <xacro:leg_gazebo name="right_rear" />  
  <xacro:shoulder_gazebo name="right_rear" />  

</robot>
