bool current
----
float32 foreaft
float32 leftright
float32 yaw
float32 roll
float32 pitch
float32 heave
float32 speed
float32 visYawCmd
float32 visPitchCmd
float32 visSpeedCmd
bool isSpeedValid
int32 gaitID
int32 commandWord
float32 PitchTrim
float32 RollTrim
float32 YawTrim
float32 YawGyroDrift
int32 gaitselect
int32 enableIntegration
int32 visEnable
int32 setLEDs
int32 AutopilotSelect
int32 AutopilotMode
int32 update
int32 modePause
int32 zeroDepth
int32 SetGyro
float32 SetGyroValue


float32 period
float32 oscRatio
float32 amplitude
float32 iir
float32 visYawGain
float32 visPitchGain
float32 visSpeedGain
float32 actuatorOffset
float32 GuiTargetDepth
float32 ApTargetRollCmd
float32 ApTargetPitchCmd
float32 ApTargetYawCmd
float32 GuiParam0
float32 GuiParam1
float32 GuiParam2
float32 GuiParam3
float32 GuiParam4
float32 GuiParam5
float32 GuiParam6
float32 GuiParam7
float32 GuiParam8